
[functions.signup-with-captcha]
enabled = true
verify_jwt = true
import_map = "./functions/signup-with-captcha/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/signup-with-captcha/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/signup-with-captcha/*.html" ]

[functions.login-with-captcha]
enabled = true
verify_jwt = true
import_map = "./functions/login-with-captcha/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/login-with-captcha/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/login-with-captcha/*.html" ]

[functions.update-exchange-rates]
enabled = true
verify_jwt = false
import_map = "./functions/update-exchange-rates/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-exchange-rates/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-exchange-rates/*.html" ]
